 console.log('TESTE');

 let numero = 4.56;
 let numero2 = 5.36;

 let soma = numero + numero2;

 console.log(soma)

 // arredondamento de numeros para o mais próximo
 console.log(Math.round(numero)) 
 console.log(Math.round(numero2))

// arredondamento de numeros para o sucessor
console.log(Math.ceil(numero)) 
console.log(Math.ceil(numero2))

// arredondamento de numeros para o mais próximo
console.log(Math.pow(numero, 2)) 
console.log(Math.pow(numero2, 3))

console.log(Math.pow(5,2))//  elevação de numeros


